---
title: "Kickoff "
author: "Peter Ganong and Maggie Shi"
date: October 14, 2024
date-format: long
format: 
    beamer:
        aspectratio: 169
        theme: default
        header-includes: \renewcommand{\tightlist}{\setlength{\itemsep}{3ex}\setlength{\parskip}{0pt}}
            \setbeamertemplate{footline}[frame number]
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
---

## MUD cards and other feedback
* Quiz at lab is about lecture content from the same week. 
    * Although it is true that (a) problem sets require you to go beyond lecture and also that (b) lecture content has URLs, the quizzes will not go beyond what is covered in lecture. Thanks for clarifying Surya and anon!
* Going forward, will separate out every single subquestion on problem sets. We chose not to renumber because subsequent changes can mess this up. Thanks Neil for the suggestion!
* Survey results on lecture speed and in-class exercises vs frontal lecture

## MUD cards II 

* How to handle when you have made changes to your forked repo and we have made changes to the parent repo 
    * Commit your work
    * Pull (GitHub desktop calls this "fetch")
    * Push your commit 
* What if both parties have modified the same file? A merge conflict! 
    * Will cover this in depth soon. 
    * For now, just use any tool you find. For conflicts in text files like `.qmd`, use VSCode or a pull request on GitHub.com. For conflicts in non-knitted files like PDFs, you need to pick one version. This is usually done most easily at the command line, but if you are stuck this is a good question to bring to lab, office hours, ask during a break from class. 

## MUD cards III / Ed

* Many students are having trouble accepting the PS2 assignment
* I (Peter) actually broke the assignment when trying to help a student troubleshoot
* **[Here](https://classroom.github.com/a/Yr0cZD8n)** is a new link you can use
    * https://classroom.github.com/a/Yr0cZD8n
* If you already have accepted the assignment at the old link (1/2 of the class), you do not need to do anything different.


## Final project
* Final project parameters now up on repo under `ps/final_project` folder
* Key details
\vspace{2ex}
    * 70\% coding, 15\% writeup, 15\% presentation
    * Groups of up to 3, can be across sections but all members must be able to attend presentation slot
* Key dates:
\vspace{2ex}
    * Nov. 1: submit Canvas quiz to declare topic + group members. Meet with instructors/head TA (optional).
    * Dec. 2-5: in-class presentations
    * Dec. 7: submit final repository and writeup 