---
title: "Kickoff (Tue/Thurs Sections)"
author: "Peter Ganong and Maggie Shi"
date: October 3, 2024
date-format: long
format: 
    beamer:
        aspectratio: 169
        theme: default
        header-includes: \renewcommand{\tightlist}{\setlength{\itemsep}{3ex}\setlength{\parskip}{0pt}}
            \setbeamertemplate{footline}[frame number]
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
---

### MUD cards: admin
- Questions about how to download HTML of lecture notes
\vspace{2ex}
    - See https://github.com/uchicago-harris-dap/ppha30538_fall2024 homepage to pull all lecture files, including HTML
- Questions about other github setup (e.g. forking)
\vspace{2ex}
    - See revised instructions in lecture 0
    - Also, 104 forks created as of Tuesday night so most folks are figuring it out. If you haven't yet, ask a friend
- Questions about Visual studio and Quarto
\vspace{2ex}
    - Ozzy posted a recording of mini-lesson from Wednesday's lab - see Canvas
    - And will repeat it in today's lab

### MUD cards: content 
- Is JSON something we'll need to write or regularly refer to?
\vspace{2ex}
    - No, it's mostly working in the background. But it's good to know how to read it since a lot of data is stored as JSON as well
- What does it mean for Vega and Vega-lite to be "grammars"?
\vspace{2ex}
    - A grammar is a formal set of rules/structure for creating visualizations, where the structure of the code specifies what the visualization represents as opposed to just telling Python how to "draw" it.
    - A grammar isn't anything specific to Python 
    - And will only come up in visualization in this course

### MUD cards
- As an aside: MUD cards have already proven to be really useful!
- Teaching team hadn't realized the quick turnaround required between teaching VSCode at Thursday lab and the Saturday problem set deadline until it was brought up in the MUD cards
- We were able to respond and put up a recording on Wednesday
- So keep them coming :)

### Backside of a MUD card
* Name
* At least one professional fact
* At least one personal fact

\vspace{2ex}
Feel free to grab another MUD card if you want to ask an anonymous question!