---
title: "Kickoff"
author: "Peter Ganong and Maggie Shi"
date: today
date-format: long
format: 
    beamer:
        aspectratio: 169
        theme: default
        header-includes: \renewcommand{\tightlist}{\setlength{\itemsep}{3ex}\setlength{\parskip}{0pt}}
            \setbeamertemplate{footline}[frame number]
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
---

### MUD cards
- Questions about how to download HTML of lecture notes
    - See https://github.com/uchicago-harris-dap/ppha30538_fall2024 homepage
- Questions about other github setup (e.g. forking)
    - See revised instructions in lecture 0
    - Also, 104 forks created as of Tuesday night so most folks are figuring it out. If you haven't yet, ask a friend
- Questions about visual studio and quarto
    - Minilesson at lab today

### Admin
- Simplified quiz content -- each week's quiz will be material from that week (plus, in this week's case, some review of DAP1 and some integrity policy questions)
- (9AM Wed only) “We ask that phones remain in your backpack. If you need to use your phone, please first step out of the classroom.”

### Who am I? (Peter)

* Professional
    * Now: most of my research is on income volatility and consumption smoothing, side interest in meta-analysis
    * Past research: foreclosure crisis, housing vouchers, migration/land use regulation, SNAP
* Personal 
    * Boston almost continuously until 30 (“Hub of the Universe”)
    * Fun fact: got engaged at the finish line of Boston Marathon.
* Big fan of gap years
    * Religious studies in Israel between high school and college
    * White House Council of Economic Advisers between college and grad school
    * Boston City Hall as leave of absence from grad school.

### How did this course come about? (Peter)

* Wasn't sure what I wanted to do after my PhD so I took a year off to work in city hall
* Ended up in the IT department (really!) helping to start a Citywide Analytics Team
* At that point in time, the City didn't need stats or causal inference or economics...
* But it did need data cleaning (DAP I), data visualization (DAP II), and lots of dashboards (DAP II)


### Backside of your MUD cards

* Name
* At least one professional fact
* At least one personal fact